"use client";

import { useEffect } from "react";

// 24 realistic products for 8 car brands (3 products each)
const OZGUR_MOTOR_PRODUCTS = [
  // 1. Toyota (Warehouse: "Toyota Deposu", Zone: "T")
  {
    id: "prod-toyota-1",
    itemType: "product",
    name: "Toyota Prius Ön Z-Link Rot Mili",
    category: "Yedek Parça",
    brand: "Toyota",
    model: "Prius 2016-2020",
    description: "Ön süspansiyon ve direksiyon kararlılığı için yüksek dayanımlı Z-Link rot mili.",
    purchasePrice: "95.00",
    salePrice: "185.00",
    currency: "GEL",
    barcode: "8691012345014",
    qrCode: "QR-TYT-ROT-MILI",
    sku: "TYT-PR-ROT-MILI",
    oemCode: "48820-52030",
    manufacturerCode: "555-SL-T020",
    stockTracking: true,
    quantity: "24",
    warehouse: "Toyota Deposu",
    shelf: "T-01-01",
    entryDate: "2026-06-15",
    exitDate: "",
    pricingMode: "fixed",
    visibility: "visible",
    imageUrl: "/product-images/part.svg",
    videoUrl: "",
    variants: [],
    galleryUrls: ["/product-images/part.svg"]
  },
  {
    id: "prod-toyota-2",
    itemType: "product",
    name: "Toyota Land Cruiser Ön Fren Balata Takımı",
    category: "Fren Sistemi",
    brand: "Toyota",
    model: "Land Cruiser Prado 150",
    description: "Ağır hizmet tipi, seramik alaşımlı yüksek performanslı ön fren balata seti.",
    purchasePrice: "150.00",
    salePrice: "290.00",
    currency: "GEL",
    barcode: "8691012345021",
    qrCode: "QR-TYT-LC-BALATA",
    sku: "TYT-LC-FREN-BALATASI",
    oemCode: "04465-60320",
    manufacturerCode: "TRW-GDB3525",
    stockTracking: true,
    quantity: "12",
    warehouse: "Toyota Deposu",
    shelf: "T-01-02",
    entryDate: "2026-06-18",
    exitDate: "",
    pricingMode: "fixed",
    visibility: "visible",
    imageUrl: "/product-images/part.svg",
    videoUrl: "",
    variants: [],
    galleryUrls: ["/product-images/part.svg"]
  },
  {
    id: "prod-toyota-3",
    itemType: "product",
    name: "Toyota Yaris Hava Filtresi",
    category: "Bakım Malzemeleri",
    brand: "Toyota",
    model: "Yaris 1.33 Dual VVT-i",
    description: "Motor yanma odasına giren havayı mikro partiküllerden arındıran yüksek süzme kapasiteli filtre.",
    purchasePrice: "25.00",
    salePrice: "55.00",
    currency: "GEL",
    barcode: "8691012345038",
    qrCode: "QR-TYT-HAVA-FILT",
    sku: "TYT-YARIS-HAVA-FILTRE",
    oemCode: "17801-21050",
    manufacturerCode: "MANN-C26003",
    stockTracking: true,
    quantity: "40",
    warehouse: "Toyota Deposu",
    shelf: "T-02-01",
    entryDate: "2026-06-20",
    exitDate: "",
    pricingMode: "fixed",
    visibility: "visible",
    imageUrl: "/product-images/part.svg",
    videoUrl: "",
    variants: [],
    galleryUrls: ["/product-images/part.svg"]
  },

  // 2. Mercedes-Benz (Warehouse: "Mercedes-Benz Deposu", Zone: "M")
  {
    id: "prod-mercedes-1",
    itemType: "product",
    name: "Mercedes E-Class W213 Havalandırmalı Ön Fren Diski",
    category: "Fren Sistemi",
    brand: "Mercedes-Benz",
    model: "E-Class W213",
    description: "Yüksek hızlarda maksimum soğutma sağlayan delikli ve havalandırmalı çelik fren diski.",
    purchasePrice: "320.00",
    salePrice: "580.00",
    currency: "GEL",
    barcode: "8691012345045",
    qrCode: "QR-MER-FREN-DISK",
    sku: "MER-W213-FREN-DISK",
    oemCode: "0004212212",
    manufacturerCode: "BREMBO-09.C404.13",
    stockTracking: true,
    quantity: "8",
    warehouse: "Mercedes-Benz Deposu",
    shelf: "M-01-01",
    entryDate: "2026-06-10",
    exitDate: "",
    pricingMode: "fixed",
    visibility: "visible",
    imageUrl: "/product-images/part.svg",
    videoUrl: "",
    variants: [],
    galleryUrls: ["/product-images/part.svg"]
  },
  {
    id: "prod-mercedes-2",
    itemType: "product",
    name: "Mercedes C-Class Yağ Filtre Elemanı",
    category: "Bakım Malzemeleri",
    brand: "Mercedes-Benz",
    model: "C200 d W205",
    description: "Motor yağı içerisindeki metal ve karbon tortularını süzen orijinal yağ filtresi.",
    purchasePrice: "40.00",
    salePrice: "90.00",
    currency: "GEL",
    barcode: "8691012345052",
    qrCode: "QR-MER-YAG-FILT",
    sku: "MER-C200-YAG-FILTRE",
    oemCode: "6541801100",
    manufacturerCode: "HENGST-E822H",
    stockTracking: true,
    quantity: "30",
    warehouse: "Mercedes-Benz Deposu",
    shelf: "M-01-02",
    entryDate: "2026-06-25",
    exitDate: "",
    pricingMode: "fixed",
    visibility: "visible",
    imageUrl: "/product-images/part.svg",
    videoUrl: "",
    variants: [],
    galleryUrls: ["/product-images/part.svg"]
  },
  {
    id: "prod-mercedes-3",
    itemType: "product",
    name: "Mercedes Sprinter Ön Amortisör Sol",
    category: "Süspansiyon",
    brand: "Mercedes-Benz",
    model: "Sprinter 3-t (906)",
    description: "Ağır yük taşımacılığına uygun, darbe emiş gücü yüksek gazlı amortisör.",
    purchasePrice: "210.00",
    salePrice: "390.00",
    currency: "GEL",
    barcode: "8691012345069",
    qrCode: "QR-MER-AMORTISOR",
    sku: "MER-SPR-AMORTISOR",
    oemCode: "9063200230",
    manufacturerCode: "SACHS-314227",
    stockTracking: true,
    quantity: "10",
    warehouse: "Mercedes-Benz Deposu",
    shelf: "M-02-01",
    entryDate: "2026-06-12",
    exitDate: "",
    pricingMode: "fixed",
    visibility: "visible",
    imageUrl: "/product-images/part.svg",
    videoUrl: "",
    variants: [],
    galleryUrls: ["/product-images/part.svg"]
  },

  // 3. BMW (Warehouse: "BMW Deposu", Zone: "B")
  {
    id: "prod-bmw-1",
    itemType: "product",
    name: "BMW 5 Series G30 Çift İridyum Buji Seti",
    category: "Ateşleme Sistemi",
    brand: "BMW",
    model: "530i G30 B48",
    description: "B48 LCI motorlar için yüksek ateşleme verimliliği sağlayan çift iridyum buji takımı.",
    purchasePrice: "140.00",
    salePrice: "260.00",
    currency: "GEL",
    barcode: "8691012345076",
    qrCode: "QR-BMW-G30-BUJI",
    sku: "BMW-G30-BUJI",
    oemCode: "12122455555",
    manufacturerCode: "NGK-SILZKGR8B8S",
    stockTracking: true,
    quantity: "18",
    warehouse: "BMW Deposu",
    shelf: "B-01-01",
    entryDate: "2026-06-08",
    exitDate: "",
    pricingMode: "fixed",
    visibility: "visible",
    imageUrl: "/product-images/part.svg",
    videoUrl: "",
    variants: [],
    galleryUrls: ["/product-images/part.svg"]
  },
  {
    id: "prod-bmw-2",
    itemType: "product",
    name: "BMW 3 Series F30 Devirdaimli Termostat Ünitesi",
    category: "Soğutma Sistemi",
    brand: "BMW",
    model: "320i F30 N13",
    description: "Motor çalışma sıcaklığını ideal düzeyde tutan gövdeli termostat devirdaim ünitesi.",
    purchasePrice: "190.00",
    salePrice: "340.00",
    currency: "GEL",
    barcode: "8691012345083",
    qrCode: "QR-BMW-TERMOSTAT",
    sku: "BMW-F30-TERMOSTAT",
    oemCode: "11537600584",
    manufacturerCode: "MAHLE-TM14103",
    stockTracking: true,
    quantity: "6",
    warehouse: "BMW Deposu",
    shelf: "B-01-02",
    entryDate: "2026-06-22",
    exitDate: "",
    pricingMode: "fixed",
    visibility: "visible",
    imageUrl: "/product-images/part.svg",
    videoUrl: "",
    variants: [],
    galleryUrls: ["/product-images/part.svg"]
  },
  {
    id: "prod-bmw-3",
    itemType: "product",
    name: "BMW 3 Series E90 Krank Kasnağı",
    category: "Motor Parçaları",
    brand: "BMW",
    model: "320d E90 N47",
    description: "N47 motor kodlu dizel araçlar için vibrasyon önleyici krank kasnağı damper ünitesi.",
    purchasePrice: "280.00",
    salePrice: "490.00",
    currency: "GEL",
    barcode: "8691012345090",
    qrCode: "QR-BMW-KRANK-KASNAK",
    sku: "BMW-E90-KASNAK",
    oemCode: "11237797995",
    manufacturerCode: "CORTECO-80000374",
    stockTracking: true,
    quantity: "5",
    warehouse: "BMW Deposu",
    shelf: "B-02-01",
    entryDate: "2026-06-14",
    exitDate: "",
    pricingMode: "fixed",
    visibility: "visible",
    imageUrl: "/product-images/part.svg",
    videoUrl: "",
    variants: [],
    galleryUrls: ["/product-images/part.svg"]
  },

  // 4. Opel (Warehouse: "Opel Deposu", Zone: "O")
  {
    id: "prod-opel-1",
    itemType: "product",
    name: "Opel Astra J Ateşleme Bobini",
    category: "Ateşleme Sistemi",
    brand: "Opel",
    model: "Astra J 1.4 Turbo",
    description: "A14NET/B14NET motorlu Astra J araçlar için 4'lü blok ateşleme bobin modülü.",
    purchasePrice: "180.00",
    salePrice: "310.00",
    currency: "GEL",
    barcode: "8691012345106",
    qrCode: "QR-OPL-AST-BOBIN",
    sku: "OPL-AST-BOBIN",
    oemCode: "1208098",
    manufacturerCode: "DELPHI-CE20009",
    stockTracking: true,
    quantity: "15",
    warehouse: "Opel Deposu",
    shelf: "O-01-01",
    entryDate: "2026-06-11",
    exitDate: "",
    pricingMode: "fixed",
    visibility: "visible",
    imageUrl: "/product-images/part.svg",
    videoUrl: "",
    variants: [],
    galleryUrls: ["/product-images/part.svg"]
  },
  {
    id: "prod-opel-2",
    itemType: "product",
    name: "Opel Vectra C Su Pompası (Devirdaim)",
    category: "Soğutma Sistemi",
    brand: "Opel",
    model: "Vectra C 1.6 16V",
    description: "Z16XEP motor uyumlu, sızdırmazlık contalı alüminyum gövde su devirdaim pompası.",
    purchasePrice: "65.00",
    salePrice: "120.00",
    currency: "GEL",
    barcode: "8691012345113",
    qrCode: "QR-OPL-VEC-POMP",
    sku: "OPL-VEC-DEVIRDAIM",
    oemCode: "1334142",
    manufacturerCode: "GRAF-PA899",
    stockTracking: true,
    quantity: "20",
    warehouse: "Opel Deposu",
    shelf: "O-01-02",
    entryDate: "2026-06-21",
    exitDate: "",
    pricingMode: "fixed",
    visibility: "visible",
    imageUrl: "/product-images/part.svg",
    videoUrl: "",
    variants: [],
    galleryUrls: ["/product-images/part.svg"]
  },
  {
    id: "prod-opel-3",
    itemType: "product",
    name: "Opel Corsa D Debriyaj Seti Baskı Balata",
    category: "Debriyaj Sistemi",
    brand: "Opel",
    model: "Corsa D 1.3 CDTI",
    description: "Dizel Corsa D araçlar için debriyaj baskısı, balatası ve hidrolik debriyaj rulmanı içeren set.",
    purchasePrice: "290.00",
    salePrice: "480.00",
    currency: "GEL",
    barcode: "8691012345120",
    qrCode: "QR-OPL-COR-DEB",
    sku: "OPL-COR-DEBRIYAJ",
    oemCode: "6606019",
    manufacturerCode: "LUK-622312633",
    stockTracking: true,
    quantity: "8",
    warehouse: "Opel Deposu",
    shelf: "O-02-01",
    entryDate: "2026-06-05",
    exitDate: "",
    pricingMode: "fixed",
    visibility: "visible",
    imageUrl: "/product-images/part.svg",
    videoUrl: "",
    variants: [],
    galleryUrls: ["/product-images/part.svg"]
  },

  // 5. Ford (Warehouse: "Ford Deposu", Zone: "F")
  {
    id: "prod-ford-1",
    itemType: "product",
    name: "Ford Transit Euro 5 Dizel Enjektör Takımı",
    category: "Yakıt Sistemi",
    brand: "Ford",
    model: "Transit 2.2 TDCi",
    description: "Euro 5 standartlarında yüksek basınçlı püskürtme yapan orijinal common-rail yakıt enjektörü.",
    purchasePrice: "450.00",
    salePrice: "790.00",
    currency: "GEL",
    barcode: "8691012345137",
    qrCode: "QR-FRD-TRA-ENJ",
    sku: "FRD-TRA-ENJEKTOR",
    oemCode: "BK2Q-9K546-AG",
    manufacturerCode: "DENSO-095000-982",
    stockTracking: true,
    quantity: "16",
    warehouse: "Ford Deposu",
    shelf: "F-01-01",
    entryDate: "2026-06-18",
    exitDate: "",
    pricingMode: "fixed",
    visibility: "visible",
    imageUrl: "/product-images/part.svg",
    videoUrl: "",
    variants: [],
    galleryUrls: ["/product-images/part.svg"]
  },
  {
    id: "prod-ford-2",
    itemType: "product",
    name: "Ford Focus Triger Kayış Seti Su Pompalı",
    category: "Motor Parçaları",
    brand: "Ford",
    model: "Focus 1.6 Ti-VCT",
    description: "Focus benzinli motorlar için gergi bilyası, devirdaim su pompası ve triger kayışı seti.",
    purchasePrice: "110.00",
    salePrice: "210.00",
    currency: "GEL",
    barcode: "8691012345144",
    qrCode: "QR-FRD-FOC-TRG",
    sku: "FRD-FOC-TRIGER",
    oemCode: "1865664",
    manufacturerCode: "GATES-KP15669XS",
    stockTracking: true,
    quantity: "22",
    warehouse: "Ford Deposu",
    shelf: "F-01-02",
    entryDate: "2026-06-19",
    exitDate: "",
    pricingMode: "fixed",
    visibility: "visible",
    imageUrl: "/product-images/part.svg",
    videoUrl: "",
    variants: [],
    galleryUrls: ["/product-images/part.svg"]
  },
  {
    id: "prod-ford-3",
    itemType: "product",
    name: "Ford Mondeo Arka Fren Balata Takımı",
    category: "Fren Sistemi",
    brand: "Ford",
    model: "Mondeo Mk5 2.0 TDCi",
    description: "Elektrikli park freni uyumlu, yüksek sürtünme katsayısına sahip tozsuz arka balata seti.",
    purchasePrice: "80.00",
    salePrice: "155.00",
    currency: "GEL",
    barcode: "8691012345151",
    qrCode: "QR-FRD-MON-BAL",
    sku: "FRD-MON-FREN-BALATA",
    oemCode: "DG9C-2M008-AA",
    manufacturerCode: "ATE-13.0460-7294.2",
    stockTracking: true,
    quantity: "25",
    warehouse: "Ford Deposu",
    shelf: "F-02-01",
    entryDate: "2026-06-26",
    exitDate: "",
    pricingMode: "fixed",
    visibility: "visible",
    imageUrl: "/product-images/part.svg",
    videoUrl: "",
    variants: [],
    galleryUrls: ["/product-images/part.svg"]
  },

  // 6. Subaru (Warehouse: "Subaru Deposu", Zone: "S")
  {
    id: "prod-subaru-1",
    itemType: "product",
    name: "Subaru Forester Külbütör Subap Kapak Conta Seti",
    category: "Motor Parçaları",
    brand: "Subaru",
    model: "Forester 2.0 EJ20",
    description: "EJ20 Boxer motorlar için sol ve sağ silindir subap kapak contaları ve buji yatağı keçeleri.",
    purchasePrice: "60.00",
    salePrice: "115.00",
    currency: "GEL",
    barcode: "8691012345168",
    qrCode: "QR-SUB-FOR-CONTA",
    sku: "SUB-FOR-KAPAK-CONTA",
    oemCode: "13294AA070",
    manufacturerCode: "STONE-JC31114",
    stockTracking: true,
    quantity: "14",
    warehouse: "Subaru Deposu",
    shelf: "S-01-01",
    entryDate: "2026-06-13",
    exitDate: "",
    pricingMode: "fixed",
    visibility: "visible",
    imageUrl: "/product-images/part.svg",
    videoUrl: "",
    variants: [],
    galleryUrls: ["/product-images/part.svg"]
  },
  {
    id: "prod-subaru-2",
    itemType: "product",
    name: "Subaru Outback Ön Sol Komple Aks Mili",
    category: "Aktarma Organları",
    brand: "Subaru",
    model: "Outback 2.5 i",
    description: "AWD çekiş sistemine özel, körüklü ve greslenmiş yüksek mukavemetli komple ön aks mili.",
    purchasePrice: "310.00",
    salePrice: "560.00",
    currency: "GEL",
    barcode: "8691012345175",
    qrCode: "QR-SUB-OUT-AKS",
    sku: "SUB-OUT-AKS-MILI",
    oemCode: "28321AJ03A",
    manufacturerCode: "HDK-SU-024",
    stockTracking: true,
    quantity: "4",
    warehouse: "Subaru Deposu",
    shelf: "S-01-02",
    entryDate: "2026-06-07",
    exitDate: "",
    pricingMode: "fixed",
    visibility: "visible",
    imageUrl: "/product-images/part.svg",
    videoUrl: "",
    variants: [],
    galleryUrls: ["/product-images/part.svg"]
  },
  {
    id: "prod-subaru-3",
    itemType: "product",
    name: "Subaru Impreza MAF Sensörü",
    category: "Elektrik ve Sensörler",
    brand: "Subaru",
    model: "Impreza WRX 2.5",
    description: "Emme manifolduna giren hava miktarını ölçen yüksek hassasiyetli MAF sensörü.",
    purchasePrice: "195.00",
    salePrice: "350.00",
    currency: "GEL",
    barcode: "8691012345182",
    qrCode: "QR-SUB-IMP-MAF",
    sku: "SUB-IMP-HAVA-AKIS",
    oemCode: "22680AA310",
    manufacturerCode: "DENSO-197400-2090",
    stockTracking: true,
    quantity: "9",
    warehouse: "Subaru Deposu",
    shelf: "S-02-01",
    entryDate: "2026-06-24",
    exitDate: "",
    pricingMode: "fixed",
    visibility: "visible",
    imageUrl: "/product-images/part.svg",
    videoUrl: "",
    variants: [],
    galleryUrls: ["/product-images/part.svg"]
  },

  // 7. Honda (Warehouse: "Honda Deposu", Zone: "H")
  {
    id: "prod-honda-1",
    itemType: "product",
    name: "Honda Civic VTEC Selenoid Valf Contası",
    category: "Motor Parçaları",
    brand: "Honda",
    model: "Civic 1.6 VTEC VTi",
    description: "B16 / D16 motor VTEC selenoid gövdesi için süzgeçli filtreli orijinal yağ contası.",
    purchasePrice: "20.00",
    salePrice: "45.00",
    currency: "GEL",
    barcode: "8691012345199",
    qrCode: "QR-HON-CIV-VTEC",
    sku: "HON-CIV-VTEC-SELENOID",
    oemCode: "15825-P2M-005",
    manufacturerCode: "HONDA-OEM-GENUINE",
    stockTracking: true,
    quantity: "35",
    warehouse: "Honda Deposu",
    shelf: "H-01-01",
    entryDate: "2026-06-15",
    exitDate: "",
    pricingMode: "fixed",
    visibility: "visible",
    imageUrl: "/product-images/part.svg",
    videoUrl: "",
    variants: [],
    galleryUrls: ["/product-images/part.svg"]
  },
  {
    id: "prod-honda-2",
    itemType: "product",
    name: "Honda ATF-DW1 Otomatik Şanzıman Yağı",
    category: "Sıvılar ve Yağlar",
    brand: "Honda",
    model: "CR-V 2.0 i-VTEC",
    description: "Honda otomatik şanzımanlarına özel üretilmiş, vites geçişlerini yumuşatan DW-1 şanzıman yağı.",
    purchasePrice: "35.00",
    salePrice: "75.00",
    currency: "GEL",
    barcode: "8691012345205",
    qrCode: "QR-HON-DW1-OIL",
    sku: "HON-CRV-SANZIMAN-YAGI",
    oemCode: "08200-9008",
    manufacturerCode: "HONDA-FLUIDS",
    stockTracking: true,
    quantity: "48",
    warehouse: "Honda Deposu",
    shelf: "H-01-02",
    entryDate: "2026-06-28",
    exitDate: "",
    pricingMode: "fixed",
    visibility: "visible",
    imageUrl: "/product-images/part.svg",
    videoUrl: "",
    variants: [],
    galleryUrls: ["/product-images/part.svg"]
  },
  {
    id: "prod-honda-3",
    itemType: "product",
    name: "Honda Fit Ateşleme Bobini Arka",
    category: "Ateşleme Sistemi",
    brand: "Honda",
    model: "Fit 1.4 i-DSI",
    description: "i-DSI motorlu Fit/Jazz araçların silindir başı arka tarafta kalan 4'lü buji ateşleme bobinlerinden biri.",
    purchasePrice: "110.00",
    salePrice: "195.00",
    currency: "GEL",
    barcode: "8691012345212",
    qrCode: "QR-HON-FIT-BOBIN",
    sku: "HON-FIT-BOBIN",
    oemCode: "30521-PWA-003",
    manufacturerCode: "HITACHI-U09006",
    stockTracking: true,
    quantity: "16",
    warehouse: "Honda Deposu",
    shelf: "H-02-01",
    entryDate: "2026-06-16",
    exitDate: "",
    pricingMode: "fixed",
    visibility: "visible",
    imageUrl: "/product-images/part.svg",
    videoUrl: "",
    variants: [],
    galleryUrls: ["/product-images/part.svg"]
  },

  // 8. Hyundai (Warehouse: "Hyundai Deposu", Zone: "Y")
  {
    id: "prod-hyundai-1",
    itemType: "product",
    name: "Hyundai Elantra Dış Aks Körük Seti",
    category: "Aktarma Organları",
    brand: "Hyundai",
    model: "Elantra 1.6 CRDi",
    description: "Tekerlek tarafı dış aks mafsalı koruyucu plastik körük, kelepçeleri ve özel aks gresi seti.",
    purchasePrice: "18.00",
    salePrice: "40.00",
    currency: "GEL",
    barcode: "8691012345229",
    qrCode: "QR-HYU-ELA-KORUK",
    sku: "HYU-ELA-AKS-KORUGU",
    oemCode: "49541-2L000",
    manufacturerCode: "SKF-VKJP3147",
    stockTracking: true,
    quantity: "50",
    warehouse: "Hyundai Deposu",
    shelf: "Y-01-01",
    entryDate: "2026-06-14",
    exitDate: "",
    pricingMode: "fixed",
    visibility: "visible",
    imageUrl: "/product-images/part.svg",
    videoUrl: "",
    variants: [],
    galleryUrls: ["/product-images/part.svg"]
  },
  {
    id: "prod-hyundai-2",
    itemType: "product",
    name: "Hyundai Accent Komple Hidrolik Direksiyon Kutusu",
    category: "Direksiyon Sistemi",
    brand: "Hyundai",
    model: "Accent Era 1.5 CRDi",
    description: "Accent Era dizel araçlar için rot kolları ve rot başları dahil komple hidrolik direksiyon dişli kutusu.",
    purchasePrice: "350.00",
    salePrice: "690.00",
    currency: "GEL",
    barcode: "8691012345236",
    qrCode: "QR-HYU-ACC-KUTU",
    sku: "HYU-ACC-DIREKSIYON-KUTU",
    oemCode: "57700-1G000",
    manufacturerCode: "MANDO-EX577001G000",
    stockTracking: true,
    quantity: "6",
    warehouse: "Hyundai Deposu",
    shelf: "Y-01-02",
    entryDate: "2026-06-03",
    exitDate: "",
    pricingMode: "fixed",
    visibility: "visible",
    imageUrl: "/product-images/part.svg",
    videoUrl: "",
    variants: [],
    galleryUrls: ["/product-images/part.svg"]
  },
  {
    id: "prod-hyundai-3",
    itemType: "product",
    name: "Hyundai Santa Fe Polen Filtresi",
    category: "Bakım Malzemeleri",
    brand: "Hyundai",
    model: "Santa Fe 2.2 CRDi",
    description: "Klima havalandırma kanalı için egzoz gazı ve kokuları emen aktif karbonlu kabin filtresi.",
    purchasePrice: "28.00",
    salePrice: "60.00",
    currency: "GEL",
    barcode: "8691012345243",
    qrCode: "QR-HYU-SAN-POLEN",
    sku: "HYU-SAN-POLEN-FILTRE",
    oemCode: "97133-2B010",
    manufacturerCode: "MANN-CUK26019",
    stockTracking: true,
    quantity: "30",
    warehouse: "Hyundai Deposu",
    shelf: "Y-02-01",
    entryDate: "2026-06-27",
    exitDate: "",
    pricingMode: "fixed",
    visibility: "visible",
    imageUrl: "/product-images/part.svg",
    videoUrl: "",
    variants: [],
    galleryUrls: ["/product-images/part.svg"]
  }
];

const OZGUR_MOTOR_STORE = {
  code: "ozgur-motor",
  name: "Özgür Motor",
  representative: "Özgür Özdemir",
  email: "info@ozgurmotor.com",
  password: "MOTOR61",
  address: "Kutaisi Caddesi No: 45, Batumi, Gürcistan",
  phone: "+995 599 88 77 66",
  operatingModel: "hybrid",
  isActive: true,
  warehouses: [
    { id: "wh-toyota", name: "Toyota Deposu", purpose: "Toyota yedek parça ve sarf malzemeleri", customerVisible: true, city: "Batumi", zones: ["T"], shelves: ["T-01-01", "T-01-02", "T-01-03", "T-02-01", "T-02-02", "T-02-03", "T-03-01", "T-03-02", "T-03-03"], capacity: 2000, used: 450 },
    { id: "wh-mercedes", name: "Mercedes-Benz Deposu", purpose: "Mercedes yedek parça ve sarf malzemeleri", customerVisible: true, city: "Batumi", zones: ["M"], shelves: ["M-01-01", "M-01-02", "M-01-03", "M-02-01", "M-02-02", "M-02-03"], capacity: 1500, used: 320 },
    { id: "wh-bmw", name: "BMW Deposu", purpose: "BMW yedek parça ve sarf malzemeleri", customerVisible: true, city: "Batumi", zones: ["B"], shelves: ["B-01-01", "B-01-02", "B-01-03", "B-02-01", "B-02-02", "B-02-03"], capacity: 1500, used: 280 },
    { id: "wh-opel", name: "Opel Deposu", purpose: "Opel yedek parça ve aksesuarları", customerVisible: true, city: "Batumi", zones: ["O"], shelves: ["O-01-01", "O-01-02", "O-02-01", "O-02-02"], capacity: 1000, used: 150 },
    { id: "wh-ford", name: "Ford Deposu", purpose: "Ford yedek parça ve sarf malzemeleri", customerVisible: true, city: "Batumi", zones: ["F"], shelves: ["F-01-01", "F-01-02", "F-02-01", "F-02-02"], capacity: 1200, used: 200 },
    { id: "wh-subaru", name: "Subaru Deposu", purpose: "Subaru yedek parçaları (Boxer Motor & AWD)", customerVisible: true, city: "Batumi", zones: ["S"], shelves: ["S-01-01", "S-01-02", "S-02-01", "S-02-02"], capacity: 800, used: 90 },
    { id: "wh-honda", name: "Honda Deposu", purpose: "Honda motor, şanzıman ve kaporta parçaları", customerVisible: true, city: "Batumi", zones: ["H"], shelves: ["H-01-01", "H-01-02", "H-02-01", "H-02-02"], capacity: 1000, used: 130 },
    { id: "wh-hyundai", name: "Hyundai Deposu", purpose: "Hyundai yedek parça ve bakım filtreleri", customerVisible: true, city: "Batumi", zones: ["Y"], shelves: ["Y-01-01", "Y-01-02", "Y-02-01", "Y-02-02"], capacity: 1000, used: 110 }
  ]
};

const OZGUR_MOTOR_STAFF = {
  id: "staff-ozgurmotor",
  username: "OZGURMOTOR",
  displayName: "Özgür Motor",
  role: "owner",
  storeSlugs: ["ozgur-motor"],
  password: "MOTOR61"
};

export default function DemoDataInitializer() {
  useEffect(() => {
    try {
      // 1. Initialize Stores
      const storesStr = window.localStorage.getItem("hbs-registered-stores");
      let loadedStores = storesStr ? JSON.parse(storesStr) : [];
      const hasOzgur = loadedStores.some((s: any) => s.code === "ozgur-motor");
      if (!hasOzgur) {
        loadedStores.push(OZGUR_MOTOR_STORE);
        window.localStorage.setItem("hbs-registered-stores", JSON.stringify(loadedStores));
      }

      // 2. Initialize Staff
      const staffStr = window.localStorage.getItem("hbs-store-users");
      let loadedStaff = staffStr ? JSON.parse(staffStr) : [];
      const hasStaff = loadedStaff.some((st: any) => st.username === "OZGURMOTOR");
      if (!hasStaff) {
        loadedStaff.push(OZGUR_MOTOR_STAFF);
        window.localStorage.setItem("hbs-store-users", JSON.stringify(loadedStaff));
      }

      // 3. Initialize Products
      const prodStr = window.localStorage.getItem("hbs-store-products");
      let loadedProds = prodStr ? JSON.parse(prodStr) : [];
      const hasOzgurProds = loadedProds.some((p: any) => p.id.startsWith("prod-toyota-") || p.id.startsWith("prod-mercedes-"));
      if (!hasOzgurProds) {
        const combined = [...loadedProds, ...OZGUR_MOTOR_PRODUCTS];
        window.localStorage.setItem("hbs-store-products", JSON.stringify(combined));
      }
    } catch (e) {
      console.error("DemoDataInitializer error", e);
    }
  }, []);

  return null;
}
